pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "Secure MR Demos"
include 'samples:ufo'
include 'samples:pose'
include 'samples:ufo_origin'
include 'samples:yolo_det'
include 'samples:mnistwild'
include 'samples:rubics_cube'
include 'samples:model_inspect'
include 'samples:readback'
include 'samples:whackamole'
include 'samples:stylize'
include 'samples:face_mediapipe_pipeline'
include ':spatialml-xr-utils'
project(':spatialml-xr-utils').projectDir = file('external/SpatialML-XR-Utils/spatialml-xr-utils')
